"""create vehicles table

Revision ID: 7fa86e489685
Revises: 802a7651598e
Create Date: 2026-07-16 13:05:41.236983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa86e489685'
down_revision: Union[str, Sequence[str], None] = '802a7651598e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=False),
    sa.Column('owner_address', sa.String(length=255), nullable=False),
    sa.Column('vehicle_make', sa.String(length=50), nullable=False),
    sa.Column('vehicle_model', sa.String(length=50), nullable=False),
    sa.Column('vehicle_color', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.Enum('CAR', 'SUV', 'TRUCK', 'BUS', 'MOTORCYCLE', 'OTHER', name='vehicle_type'), nullable=False),
    sa.Column('manufacture_year', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'SUSPENDED', name='vehicle_status'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expiry_date >= registration_date', name='ck_vehicle_expiry_date'),
    sa.CheckConstraint('manufacture_year >= 1900', name='ck_vehicle_manufacture_year'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
